name: flutter_sync
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  connectivity_plus: ^6.0.3
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  path_to_regexp: ^0.4.0
  internet_connection_checker_plus: ^2.3.0
  http: ^1.2.1
  flutter_easyloading: ^3.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2

flutter:
  uses-material-design: true
